### ISSUE TITLE
Error TrustManagerFactory

### ISSUE THREAD

**Issue by adriellcardoso** [elastic/found-shield-example#10]
Hello,
When mounting the TransportClient object, the following error occurs:
`Exception in thread "main" ElasticsearchException[Failed to load plugin class [org.elasticsearch.xpack.XPackPlugin]]; nested: InvocationTargetException; nested: ElasticsearchException[failed to initialize a TrustManagerFactory]; nested: SecurityException[class "org.bouncycastle.asn1.x509.Extensions"'s signer information does not match signer information of other classes in the same package];
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:384)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:104)
	at org.elasticsearch.client.transport.TransportClient.newPluginService(TransportClient.java:101)
	at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:126)
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:268)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:125)
	at org.elasticsearch.xpack.client.PreBuiltXPackTransportClient.<init>(PreBuiltXPackTransportClient.java:55)
	at org.elasticsearch.xpack.client.PreBuiltXPackTransportClient.<init>(PreBuiltXPackTransportClient.java:50)
	at org.elasticsearch.xpack.client.PreBuiltXPackTransportClient.<init>(PreBuiltXPackTransportClient.java:46)
	at org.elasticsearch.cloud.transport.example.TransportExample.run(TransportExample.java:86)
	at org.elasticsearch.cloud.transport.example.TransportExample.main(TransportExample.java:50)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:373)
	... 10 more
Caused by: ElasticsearchException[failed to initialize a TrustManagerFactory]; nested: SecurityException[class "org.bouncycastle.asn1.x509.Extensions"'s signer information does not match signer information of other classes in the same package];
	at org.elasticsearch.xpack.ssl.StoreTrustConfig.createTrustManager(StoreTrustConfig.java:57)
	at org.elasticsearch.xpack.ssl.SSLService.createSslContext(SSLService.java:378)
	at org.elasticsearch.xpack.ssl.SSLService.loadSSLConfigurations(SSLService.java:401)
	at org.elasticsearch.xpack.ssl.SSLService.<init>(SSLService.java:79)
	at org.elasticsearch.xpack.XPackPlugin.<init>(XPackPlugin.java:197)
	... 15 more
Caused by: java.lang.SecurityException: class "org.bouncycastle.asn1.x509.Extensions"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:898)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.elasticsearch.xpack.ssl.StoreTrustConfig.createTrustManager(StoreTrustConfig.java:55)
	... 19 more`

Please, can you help me?

**Comment by igor-kupczynski** [comment]
Hey, sorry for not responding earlier. We've updated the repo a couple of times since this issue and we use a different ES version now. 

I'm going to close the issue as outdated, feel free to raise a new one if you still see problems fetching the dependencies.
